[
 {"01":[
        { "thumbClass": "template-thumb-blank", "name": "01/D001","text":"资产负债表（月）" },
        { "thumbClass": "template-thumb-blank", "name": "01/D002","text":"收入费用表（月）" },
        { "thumbClass": "template-thumb-blank", "name": "01/D003","text":"净资产变动表（年）" },
        { "thumbClass": "template-thumb-blank", "name": "01/D004","text":"现金流量表（年）" },
        { "thumbClass": "template-thumb-blank", "name": "01/D005","text":"预算收入支出表（月）" },
        { "thumbClass": "template-thumb-blank", "name": "01/D006","text":"预算结转结余变动表（月）" },
        { "thumbClass": "template-thumb-blank", "name": "01/D007","text":"财政拨款预算收入支出表（月）" },
        { "thumbClass": "template-thumb-blank", "name": "01/D009","text":"收入费用明细表（月）" },
        { "thumbClass": "template-thumb-blank", "name": "01/D010","text":"资产负债表（年）" },
        { "thumbClass": "template-thumb-blank", "name": "01/D011","text":"收入费用表（年）" },
        { "thumbClass": "template-thumb-blank", "name": "01/D012","text":"收入费用明细表（年）" },
        { "thumbClass": "template-thumb-blank", "name": "01/D013","text":"医院各科室直接成本表" },
        { "thumbClass": "template-thumb-blank", "name": "01/D014","text":"医院临床服务类科室全成本表" },
        { "thumbClass": "template-thumb-blank", "name": "01/D015","text":"医院临床服务类科室全成本构成分析表" },
        { "thumbClass": "template-thumb-blank", "name": "01/D016","text":"现金流量表（月）" },
        { "thumbClass": "template-thumb-blank", "name": "01/C001","text":"货币资金" },
        { "thumbClass": "template-thumb-blank", "name": "01/C002","text":"应收账款" },
        { "thumbClass": "template-thumb-blank", "name": "01/C003","text":"应收票据" },
        { "thumbClass": "template-thumb-blank", "name": "01/C004","text":"预付账款" },
        { "thumbClass": "template-thumb-blank", "name": "01/C005","text":"其他应收款" },
        { "thumbClass": "template-thumb-blank", "name": "01/C006","text":"存货" },
        { "thumbClass": "template-thumb-blank", "name": "01/C007","text":"其他流动资产长期待摊费用" },
        { "thumbClass": "template-thumb-blank", "name": "01/C008","text":"其他非流动资产" },
        { "thumbClass": "template-thumb-blank", "name": "01/C009","text":"长期债券投资" },
        { "thumbClass": "template-thumb-blank", "name": "01/C010","text":"长期股权投资" },
        { "thumbClass": "template-thumb-blank", "name": "01/C011","text":"短期投资" },
        { "thumbClass": "template-thumb-blank", "name": "01/C012","text":"固定资产" },
        { "thumbClass": "template-thumb-blank", "name": "01/C013","text":"在建工程" },
        { "thumbClass": "template-thumb-blank", "name": "01/C014","text":"无形资产" },
        { "thumbClass": "template-thumb-blank", "name": "01/C015","text":"公共基础设施" },
        { "thumbClass": "template-thumb-blank", "name": "01/C016","text":"政府储备物资" },
        { "thumbClass": "template-thumb-blank", "name": "01/C017","text":"受托代理资产" },
        { "thumbClass": "template-thumb-blank", "name": "01/C018","text":"应付账款" },
        { "thumbClass": "template-thumb-blank", "name": "01/C019","text":"应付票据" },
        { "thumbClass": "template-thumb-blank", "name": "01/C020","text":"预收账款" },
        { "thumbClass": "template-thumb-blank", "name": "01/C021","text":"其他应付款" },
        { "thumbClass": "template-thumb-blank", "name": "01/C022","text":"长期应付款" },
        { "thumbClass": "template-thumb-blank", "name": "01/C023","text":"其他流动负债" },
        { "thumbClass": "template-thumb-blank", "name": "01/C024","text":"预计负债" },
        { "thumbClass": "template-thumb-blank", "name": "01/C025","text":"其他非流动负债" },
        { "thumbClass": "template-thumb-blank", "name": "01/C026","text":"长期借款" },
        { "thumbClass": "template-thumb-blank", "name": "01/C027","text":"短期借款" },
        { "thumbClass": "template-thumb-blank", "name": "01/C028","text":"事业收入" },
        { "thumbClass": "template-thumb-blank", "name": "01/C029","text":"非同级财政拨款收入" },
        { "thumbClass": "template-thumb-blank", "name": "01/C030","text":"其他收入" },
        { "thumbClass": "template-thumb-blank", "name": "01/C031","text":"业务活动费用（按经济分类）" },
        { "thumbClass": "template-thumb-blank", "name": "01/C032","text":"业务活动费用（按支付对象）" },
        { "thumbClass": "template-thumb-blank", "name": "01/C033","text":"单位管理费用（按经济分类）" },
        { "thumbClass": "template-thumb-blank", "name": "01/C034","text":"单位管理费用（按支付对象）" },
        { "thumbClass": "template-thumb-blank", "name": "01/C035","text":"经营费用（按经济分类）" },
        { "thumbClass": "template-thumb-blank", "name": "01/C036","text":"经营费用（按支付对象）" },
        { "thumbClass": "template-thumb-blank", "name": "01/C037","text":"其他费用" },
        { "thumbClass": "template-thumb-blank", "name": "01/C038","text":"本期费用" },
        { "thumbClass": "template-thumb-blank", "name": "01/C039","text":"本年盈余与预算结余的差异情况说明（年）" },
        { "thumbClass": "template-thumb-blank", "name": "01/C040","text":"本月盈余与预算结余的差异调节表（月）" }
 		]},
 {"04":[
        
 		]},
 {"06":[
        
 		]}
]