package com.chd.hrp.hr.dao.msg;

import com.chd.base.SqlMapper;
import com.chd.hrp.hr.entity.msg.SysMsg;
import com.chd.hrp.hr.entity.msg.SysMsgExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysMsgMapper  extends SqlMapper{
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	int countByExample(SysMsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	int deleteByExample(SysMsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	int insert(SysMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	int insertSelective(SysMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	List<SysMsg> selectByExample(SysMsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	int updateByExampleSelective(@Param("record") SysMsg record,
			@Param("example") SysMsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	int updateByExample(@Param("record") SysMsg record,
			@Param("example") SysMsgExample example);

	public List<SysMsg>selectUserPushMsg(Map<String,Object> paramMap);
    
	public List<Map<String, Object>> getUserBirthMsg(Map<String, Object> mapVo);

}