package com.chd.hrp.hr.dao.msg;

import com.chd.base.SqlMapper;
import com.chd.hrp.hr.entity.msg.SysMsgProducer;
import com.chd.hrp.hr.entity.msg.SysMsgProducerExample;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SysMsgProducerMapper extends SqlMapper{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	int countByExample(SysMsgProducerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	int deleteByExample(SysMsgProducerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	int insert(SysMsgProducer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	int insertSelective(SysMsgProducer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	List<SysMsgProducer> selectByExample(SysMsgProducerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	SysMsgProducer selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	int updateByExampleSelective(@Param("record") SysMsgProducer record,
			@Param("example") SysMsgProducerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	int updateByExample(@Param("record") SysMsgProducer record,
			@Param("example") SysMsgProducerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	int updateByPrimaryKeySelective(SysMsgProducer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	int updateByPrimaryKey(SysMsgProducer record);
}