package com.chd.hrp.hr.entity.msg;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;

public class SysMsgExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	public SysMsgExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("TITLE is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("TITLE =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("TITLE <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("TITLE >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("TITLE >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("TITLE <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("TITLE <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("TITLE like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("TITLE not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("TITLE in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("TITLE not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("TITLE between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("TITLE not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andBodyIsNull() {
			addCriterion("BODY is null");
			return (Criteria) this;
		}

		public Criteria andBodyIsNotNull() {
			addCriterion("BODY is not null");
			return (Criteria) this;
		}

		public Criteria andBodyEqualTo(String value) {
			addCriterion("BODY =", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotEqualTo(String value) {
			addCriterion("BODY <>", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyGreaterThan(String value) {
			addCriterion("BODY >", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyGreaterThanOrEqualTo(String value) {
			addCriterion("BODY >=", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyLessThan(String value) {
			addCriterion("BODY <", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyLessThanOrEqualTo(String value) {
			addCriterion("BODY <=", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyLike(String value) {
			addCriterion("BODY like", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotLike(String value) {
			addCriterion("BODY not like", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyIn(List<String> values) {
			addCriterion("BODY in", values, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotIn(List<String> values) {
			addCriterion("BODY not in", values, "body");
			return (Criteria) this;
		}

		public Criteria andBodyBetween(String value1, String value2) {
			addCriterion("BODY between", value1, value2, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotBetween(String value1, String value2) {
			addCriterion("BODY not between", value1, value2, "body");
			return (Criteria) this;
		}

		public Criteria andCreatimeIsNull() {
			addCriterion("CREATIME is null");
			return (Criteria) this;
		}

		public Criteria andCreatimeIsNotNull() {
			addCriterion("CREATIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreatimeEqualTo(Date value) {
			addCriterion("CREATIME =", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeNotEqualTo(Date value) {
			addCriterion("CREATIME <>", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeGreaterThan(Date value) {
			addCriterion("CREATIME >", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATIME >=", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeLessThan(Date value) {
			addCriterion("CREATIME <", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATIME <=", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeIn(List<Date> values) {
			addCriterion("CREATIME in", values, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeNotIn(List<Date> values) {
			addCriterion("CREATIME not in", values, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeBetween(Date value1, Date value2) {
			addCriterion("CREATIME between", value1, value2, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATIME not between", value1, value2, "creatime");
			return (Criteria) this;
		}

		public Criteria andMsgtypeIsNull() {
			addCriterion("MSGTYPE is null");
			return (Criteria) this;
		}

		public Criteria andMsgtypeIsNotNull() {
			addCriterion("MSGTYPE is not null");
			return (Criteria) this;
		}

		public Criteria andMsgtypeEqualTo(Short value) {
			addCriterion("MSGTYPE =", value, "msgtype");
			return (Criteria) this;
		}

		public Criteria andMsgtypeNotEqualTo(Short value) {
			addCriterion("MSGTYPE <>", value, "msgtype");
			return (Criteria) this;
		}

		public Criteria andMsgtypeGreaterThan(Short value) {
			addCriterion("MSGTYPE >", value, "msgtype");
			return (Criteria) this;
		}

		public Criteria andMsgtypeGreaterThanOrEqualTo(Short value) {
			addCriterion("MSGTYPE >=", value, "msgtype");
			return (Criteria) this;
		}

		public Criteria andMsgtypeLessThan(Short value) {
			addCriterion("MSGTYPE <", value, "msgtype");
			return (Criteria) this;
		}

		public Criteria andMsgtypeLessThanOrEqualTo(Short value) {
			addCriterion("MSGTYPE <=", value, "msgtype");
			return (Criteria) this;
		}

		public Criteria andMsgtypeIn(List<Short> values) {
			addCriterion("MSGTYPE in", values, "msgtype");
			return (Criteria) this;
		}

		public Criteria andMsgtypeNotIn(List<Short> values) {
			addCriterion("MSGTYPE not in", values, "msgtype");
			return (Criteria) this;
		}

		public Criteria andMsgtypeBetween(Short value1, Short value2) {
			addCriterion("MSGTYPE between", value1, value2, "msgtype");
			return (Criteria) this;
		}

		public Criteria andMsgtypeNotBetween(Short value1, Short value2) {
			addCriterion("MSGTYPE not between", value1, value2, "msgtype");
			return (Criteria) this;
		}

		public Criteria andRoleidsIsNull() {
			addCriterion("ROLEIDS is null");
			return (Criteria) this;
		}

		public Criteria andRoleidsIsNotNull() {
			addCriterion("ROLEIDS is not null");
			return (Criteria) this;
		}

		public Criteria andRoleidsEqualTo(String value) {
			addCriterion("ROLEIDS =", value, "roleids");
			return (Criteria) this;
		}

		public Criteria andRoleidsNotEqualTo(String value) {
			addCriterion("ROLEIDS <>", value, "roleids");
			return (Criteria) this;
		}

		public Criteria andRoleidsGreaterThan(String value) {
			addCriterion("ROLEIDS >", value, "roleids");
			return (Criteria) this;
		}

		public Criteria andRoleidsGreaterThanOrEqualTo(String value) {
			addCriterion("ROLEIDS >=", value, "roleids");
			return (Criteria) this;
		}

		public Criteria andRoleidsLessThan(String value) {
			addCriterion("ROLEIDS <", value, "roleids");
			return (Criteria) this;
		}

		public Criteria andRoleidsLessThanOrEqualTo(String value) {
			addCriterion("ROLEIDS <=", value, "roleids");
			return (Criteria) this;
		}

		public Criteria andRoleidsLike(String value) {
			addCriterion("ROLEIDS like", value, "roleids");
			return (Criteria) this;
		}

		public Criteria andRoleidsNotLike(String value) {
			addCriterion("ROLEIDS not like", value, "roleids");
			return (Criteria) this;
		}

		public Criteria andRoleidsIn(List<String> values) {
			addCriterion("ROLEIDS in", values, "roleids");
			return (Criteria) this;
		}

		public Criteria andRoleidsNotIn(List<String> values) {
			addCriterion("ROLEIDS not in", values, "roleids");
			return (Criteria) this;
		}

		public Criteria andRoleidsBetween(String value1, String value2) {
			addCriterion("ROLEIDS between", value1, value2, "roleids");
			return (Criteria) this;
		}

		public Criteria andRoleidsNotBetween(String value1, String value2) {
			addCriterion("ROLEIDS not between", value1, value2, "roleids");
			return (Criteria) this;
		}

		public Criteria andUseridsIsNull() {
			addCriterion("USERIDS is null");
			return (Criteria) this;
		}

		public Criteria andUseridsIsNotNull() {
			addCriterion("USERIDS is not null");
			return (Criteria) this;
		}

		public Criteria andUseridsEqualTo(String value) {
			addCriterion("USERIDS =", value, "userids");
			return (Criteria) this;
		}

		public Criteria andUseridsNotEqualTo(String value) {
			addCriterion("USERIDS <>", value, "userids");
			return (Criteria) this;
		}

		public Criteria andUseridsGreaterThan(String value) {
			addCriterion("USERIDS >", value, "userids");
			return (Criteria) this;
		}

		public Criteria andUseridsGreaterThanOrEqualTo(String value) {
			addCriterion("USERIDS >=", value, "userids");
			return (Criteria) this;
		}

		public Criteria andUseridsLessThan(String value) {
			addCriterion("USERIDS <", value, "userids");
			return (Criteria) this;
		}

		public Criteria andUseridsLessThanOrEqualTo(String value) {
			addCriterion("USERIDS <=", value, "userids");
			return (Criteria) this;
		}

		public Criteria andUseridsLike(String value) {
			addCriterion("USERIDS like", value, "userids");
			return (Criteria) this;
		}

		public Criteria andUseridsNotLike(String value) {
			addCriterion("USERIDS not like", value, "userids");
			return (Criteria) this;
		}

		public Criteria andUseridsIn(List<String> values) {
			addCriterion("USERIDS in", values, "userids");
			return (Criteria) this;
		}

		public Criteria andUseridsNotIn(List<String> values) {
			addCriterion("USERIDS not in", values, "userids");
			return (Criteria) this;
		}

		public Criteria andUseridsBetween(String value1, String value2) {
			addCriterion("USERIDS between", value1, value2, "userids");
			return (Criteria) this;
		}

		public Criteria andUseridsNotBetween(String value1, String value2) {
			addCriterion("USERIDS not between", value1, value2, "userids");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNull() {
			addCriterion("GROUP_ID is null");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNotNull() {
			addCriterion("GROUP_ID is not null");
			return (Criteria) this;
		}

		public Criteria andGroupIdEqualTo(BigDecimal value) {
			addCriterion("GROUP_ID =", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotEqualTo(BigDecimal value) {
			addCriterion("GROUP_ID <>", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThan(BigDecimal value) {
			addCriterion("GROUP_ID >", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("GROUP_ID >=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThan(BigDecimal value) {
			addCriterion("GROUP_ID <", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("GROUP_ID <=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIn(List<BigDecimal> values) {
			addCriterion("GROUP_ID in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotIn(List<BigDecimal> values) {
			addCriterion("GROUP_ID not in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("GROUP_ID between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("GROUP_ID not between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andHosIdIsNull() {
			addCriterion("HOS_ID is null");
			return (Criteria) this;
		}

		public Criteria andHosIdIsNotNull() {
			addCriterion("HOS_ID is not null");
			return (Criteria) this;
		}

		public Criteria andHosIdEqualTo(BigDecimal value) {
			addCriterion("HOS_ID =", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdNotEqualTo(BigDecimal value) {
			addCriterion("HOS_ID <>", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdGreaterThan(BigDecimal value) {
			addCriterion("HOS_ID >", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("HOS_ID >=", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdLessThan(BigDecimal value) {
			addCriterion("HOS_ID <", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("HOS_ID <=", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdIn(List<BigDecimal> values) {
			addCriterion("HOS_ID in", values, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdNotIn(List<BigDecimal> values) {
			addCriterion("HOS_ID not in", values, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("HOS_ID between", value1, value2, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("HOS_ID not between", value1, value2, "hosId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SYS_MSG
	 * @mbggenerated  Thu Jan 03 15:17:25 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS_MSG
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 20 15:25:34 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}