package com.chd.hrp.hr.entity.msg;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysMsgProducerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public SysMsgProducerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNull() {
			addCriterion("GROUP_ID is null");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNotNull() {
			addCriterion("GROUP_ID is not null");
			return (Criteria) this;
		}

		public Criteria andGroupIdEqualTo(Integer value) {
			addCriterion("GROUP_ID =", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotEqualTo(Integer value) {
			addCriterion("GROUP_ID <>", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThan(Integer value) {
			addCriterion("GROUP_ID >", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("GROUP_ID >=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThan(Integer value) {
			addCriterion("GROUP_ID <", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThanOrEqualTo(Integer value) {
			addCriterion("GROUP_ID <=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIn(List<Integer> values) {
			addCriterion("GROUP_ID in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotIn(List<Integer> values) {
			addCriterion("GROUP_ID not in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdBetween(Integer value1, Integer value2) {
			addCriterion("GROUP_ID between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotBetween(Integer value1, Integer value2) {
			addCriterion("GROUP_ID not between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andHosIdIsNull() {
			addCriterion("HOS_ID is null");
			return (Criteria) this;
		}

		public Criteria andHosIdIsNotNull() {
			addCriterion("HOS_ID is not null");
			return (Criteria) this;
		}

		public Criteria andHosIdEqualTo(Integer value) {
			addCriterion("HOS_ID =", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdNotEqualTo(Integer value) {
			addCriterion("HOS_ID <>", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdGreaterThan(Integer value) {
			addCriterion("HOS_ID >", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("HOS_ID >=", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdLessThan(Integer value) {
			addCriterion("HOS_ID <", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdLessThanOrEqualTo(Integer value) {
			addCriterion("HOS_ID <=", value, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdIn(List<Integer> values) {
			addCriterion("HOS_ID in", values, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdNotIn(List<Integer> values) {
			addCriterion("HOS_ID not in", values, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdBetween(Integer value1, Integer value2) {
			addCriterion("HOS_ID between", value1, value2, "hosId");
			return (Criteria) this;
		}

		public Criteria andHosIdNotBetween(Integer value1, Integer value2) {
			addCriterion("HOS_ID not between", value1, value2, "hosId");
			return (Criteria) this;
		}

		public Criteria andCopyCodeIsNull() {
			addCriterion("COPY_CODE is null");
			return (Criteria) this;
		}

		public Criteria andCopyCodeIsNotNull() {
			addCriterion("COPY_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andCopyCodeEqualTo(String value) {
			addCriterion("COPY_CODE =", value, "copyCode");
			return (Criteria) this;
		}

		public Criteria andCopyCodeNotEqualTo(String value) {
			addCriterion("COPY_CODE <>", value, "copyCode");
			return (Criteria) this;
		}

		public Criteria andCopyCodeGreaterThan(String value) {
			addCriterion("COPY_CODE >", value, "copyCode");
			return (Criteria) this;
		}

		public Criteria andCopyCodeGreaterThanOrEqualTo(String value) {
			addCriterion("COPY_CODE >=", value, "copyCode");
			return (Criteria) this;
		}

		public Criteria andCopyCodeLessThan(String value) {
			addCriterion("COPY_CODE <", value, "copyCode");
			return (Criteria) this;
		}

		public Criteria andCopyCodeLessThanOrEqualTo(String value) {
			addCriterion("COPY_CODE <=", value, "copyCode");
			return (Criteria) this;
		}

		public Criteria andCopyCodeLike(String value) {
			addCriterion("COPY_CODE like", value, "copyCode");
			return (Criteria) this;
		}

		public Criteria andCopyCodeNotLike(String value) {
			addCriterion("COPY_CODE not like", value, "copyCode");
			return (Criteria) this;
		}

		public Criteria andCopyCodeIn(List<String> values) {
			addCriterion("COPY_CODE in", values, "copyCode");
			return (Criteria) this;
		}

		public Criteria andCopyCodeNotIn(List<String> values) {
			addCriterion("COPY_CODE not in", values, "copyCode");
			return (Criteria) this;
		}

		public Criteria andCopyCodeBetween(String value1, String value2) {
			addCriterion("COPY_CODE between", value1, value2, "copyCode");
			return (Criteria) this;
		}

		public Criteria andCopyCodeNotBetween(String value1, String value2) {
			addCriterion("COPY_CODE not between", value1, value2, "copyCode");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andProducerIsNull() {
			addCriterion("PRODUCER is null");
			return (Criteria) this;
		}

		public Criteria andProducerIsNotNull() {
			addCriterion("PRODUCER is not null");
			return (Criteria) this;
		}

		public Criteria andProducerEqualTo(String value) {
			addCriterion("PRODUCER =", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotEqualTo(String value) {
			addCriterion("PRODUCER <>", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerGreaterThan(String value) {
			addCriterion("PRODUCER >", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCER >=", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerLessThan(String value) {
			addCriterion("PRODUCER <", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerLessThanOrEqualTo(String value) {
			addCriterion("PRODUCER <=", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerLike(String value) {
			addCriterion("PRODUCER like", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotLike(String value) {
			addCriterion("PRODUCER not like", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerIn(List<String> values) {
			addCriterion("PRODUCER in", values, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotIn(List<String> values) {
			addCriterion("PRODUCER not in", values, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerBetween(String value1, String value2) {
			addCriterion("PRODUCER between", value1, value2, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotBetween(String value1, String value2) {
			addCriterion("PRODUCER not between", value1, value2, "producer");
			return (Criteria) this;
		}

		public Criteria andCronIsNull() {
			addCriterion("CRON is null");
			return (Criteria) this;
		}

		public Criteria andCronIsNotNull() {
			addCriterion("CRON is not null");
			return (Criteria) this;
		}

		public Criteria andCronEqualTo(String value) {
			addCriterion("CRON =", value, "cron");
			return (Criteria) this;
		}

		public Criteria andCronNotEqualTo(String value) {
			addCriterion("CRON <>", value, "cron");
			return (Criteria) this;
		}

		public Criteria andCronGreaterThan(String value) {
			addCriterion("CRON >", value, "cron");
			return (Criteria) this;
		}

		public Criteria andCronGreaterThanOrEqualTo(String value) {
			addCriterion("CRON >=", value, "cron");
			return (Criteria) this;
		}

		public Criteria andCronLessThan(String value) {
			addCriterion("CRON <", value, "cron");
			return (Criteria) this;
		}

		public Criteria andCronLessThanOrEqualTo(String value) {
			addCriterion("CRON <=", value, "cron");
			return (Criteria) this;
		}

		public Criteria andCronLike(String value) {
			addCriterion("CRON like", value, "cron");
			return (Criteria) this;
		}

		public Criteria andCronNotLike(String value) {
			addCriterion("CRON not like", value, "cron");
			return (Criteria) this;
		}

		public Criteria andCronIn(List<String> values) {
			addCriterion("CRON in", values, "cron");
			return (Criteria) this;
		}

		public Criteria andCronNotIn(List<String> values) {
			addCriterion("CRON not in", values, "cron");
			return (Criteria) this;
		}

		public Criteria andCronBetween(String value1, String value2) {
			addCriterion("CRON between", value1, value2, "cron");
			return (Criteria) this;
		}

		public Criteria andCronNotBetween(String value1, String value2) {
			addCriterion("CRON not between", value1, value2, "cron");
			return (Criteria) this;
		}

		public Criteria andReuserIsNull() {
			addCriterion("REUSER is null");
			return (Criteria) this;
		}

		public Criteria andReuserIsNotNull() {
			addCriterion("REUSER is not null");
			return (Criteria) this;
		}

		public Criteria andReuserEqualTo(String value) {
			addCriterion("REUSER =", value, "reuser");
			return (Criteria) this;
		}

		public Criteria andReuserNotEqualTo(String value) {
			addCriterion("REUSER <>", value, "reuser");
			return (Criteria) this;
		}

		public Criteria andReuserGreaterThan(String value) {
			addCriterion("REUSER >", value, "reuser");
			return (Criteria) this;
		}

		public Criteria andReuserGreaterThanOrEqualTo(String value) {
			addCriterion("REUSER >=", value, "reuser");
			return (Criteria) this;
		}

		public Criteria andReuserLessThan(String value) {
			addCriterion("REUSER <", value, "reuser");
			return (Criteria) this;
		}

		public Criteria andReuserLessThanOrEqualTo(String value) {
			addCriterion("REUSER <=", value, "reuser");
			return (Criteria) this;
		}

		public Criteria andReuserLike(String value) {
			addCriterion("REUSER like", value, "reuser");
			return (Criteria) this;
		}

		public Criteria andReuserNotLike(String value) {
			addCriterion("REUSER not like", value, "reuser");
			return (Criteria) this;
		}

		public Criteria andReuserIn(List<String> values) {
			addCriterion("REUSER in", values, "reuser");
			return (Criteria) this;
		}

		public Criteria andReuserNotIn(List<String> values) {
			addCriterion("REUSER not in", values, "reuser");
			return (Criteria) this;
		}

		public Criteria andReuserBetween(String value1, String value2) {
			addCriterion("REUSER between", value1, value2, "reuser");
			return (Criteria) this;
		}

		public Criteria andReuserNotBetween(String value1, String value2) {
			addCriterion("REUSER not between", value1, value2, "reuser");
			return (Criteria) this;
		}

		public Criteria andReroleIsNull() {
			addCriterion("REROLE is null");
			return (Criteria) this;
		}

		public Criteria andReroleIsNotNull() {
			addCriterion("REROLE is not null");
			return (Criteria) this;
		}

		public Criteria andReroleEqualTo(String value) {
			addCriterion("REROLE =", value, "rerole");
			return (Criteria) this;
		}

		public Criteria andReroleNotEqualTo(String value) {
			addCriterion("REROLE <>", value, "rerole");
			return (Criteria) this;
		}

		public Criteria andReroleGreaterThan(String value) {
			addCriterion("REROLE >", value, "rerole");
			return (Criteria) this;
		}

		public Criteria andReroleGreaterThanOrEqualTo(String value) {
			addCriterion("REROLE >=", value, "rerole");
			return (Criteria) this;
		}

		public Criteria andReroleLessThan(String value) {
			addCriterion("REROLE <", value, "rerole");
			return (Criteria) this;
		}

		public Criteria andReroleLessThanOrEqualTo(String value) {
			addCriterion("REROLE <=", value, "rerole");
			return (Criteria) this;
		}

		public Criteria andReroleLike(String value) {
			addCriterion("REROLE like", value, "rerole");
			return (Criteria) this;
		}

		public Criteria andReroleNotLike(String value) {
			addCriterion("REROLE not like", value, "rerole");
			return (Criteria) this;
		}

		public Criteria andReroleIn(List<String> values) {
			addCriterion("REROLE in", values, "rerole");
			return (Criteria) this;
		}

		public Criteria andReroleNotIn(List<String> values) {
			addCriterion("REROLE not in", values, "rerole");
			return (Criteria) this;
		}

		public Criteria andReroleBetween(String value1, String value2) {
			addCriterion("REROLE between", value1, value2, "rerole");
			return (Criteria) this;
		}

		public Criteria andReroleNotBetween(String value1, String value2) {
			addCriterion("REROLE not between", value1, value2, "rerole");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNull() {
			addCriterion("CREATOR is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNotNull() {
			addCriterion("CREATOR is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorEqualTo(BigDecimal value) {
			addCriterion("CREATOR =", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotEqualTo(BigDecimal value) {
			addCriterion("CREATOR <>", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThan(BigDecimal value) {
			addCriterion("CREATOR >", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("CREATOR >=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThan(BigDecimal value) {
			addCriterion("CREATOR <", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThanOrEqualTo(BigDecimal value) {
			addCriterion("CREATOR <=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorIn(List<BigDecimal> values) {
			addCriterion("CREATOR in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotIn(List<BigDecimal> values) {
			addCriterion("CREATOR not in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("CREATOR between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("CREATOR not between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatimeIsNull() {
			addCriterion("CREATIME is null");
			return (Criteria) this;
		}

		public Criteria andCreatimeIsNotNull() {
			addCriterion("CREATIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreatimeEqualTo(Date value) {
			addCriterion("CREATIME =", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeNotEqualTo(Date value) {
			addCriterion("CREATIME <>", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeGreaterThan(Date value) {
			addCriterion("CREATIME >", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATIME >=", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeLessThan(Date value) {
			addCriterion("CREATIME <", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATIME <=", value, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeIn(List<Date> values) {
			addCriterion("CREATIME in", values, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeNotIn(List<Date> values) {
			addCriterion("CREATIME not in", values, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeBetween(Date value1, Date value2) {
			addCriterion("CREATIME between", value1, value2, "creatime");
			return (Criteria) this;
		}

		public Criteria andCreatimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATIME not between", value1, value2, "creatime");
			return (Criteria) this;
		}

		public Criteria andBefordayIsNull() {
			addCriterion("BEFORDAY is null");
			return (Criteria) this;
		}

		public Criteria andBefordayIsNotNull() {
			addCriterion("BEFORDAY is not null");
			return (Criteria) this;
		}

		public Criteria andBefordayEqualTo(Short value) {
			addCriterion("BEFORDAY =", value, "beforday");
			return (Criteria) this;
		}

		public Criteria andBefordayNotEqualTo(Short value) {
			addCriterion("BEFORDAY <>", value, "beforday");
			return (Criteria) this;
		}

		public Criteria andBefordayGreaterThan(Short value) {
			addCriterion("BEFORDAY >", value, "beforday");
			return (Criteria) this;
		}

		public Criteria andBefordayGreaterThanOrEqualTo(Short value) {
			addCriterion("BEFORDAY >=", value, "beforday");
			return (Criteria) this;
		}

		public Criteria andBefordayLessThan(Short value) {
			addCriterion("BEFORDAY <", value, "beforday");
			return (Criteria) this;
		}

		public Criteria andBefordayLessThanOrEqualTo(Short value) {
			addCriterion("BEFORDAY <=", value, "beforday");
			return (Criteria) this;
		}

		public Criteria andBefordayIn(List<Short> values) {
			addCriterion("BEFORDAY in", values, "beforday");
			return (Criteria) this;
		}

		public Criteria andBefordayNotIn(List<Short> values) {
			addCriterion("BEFORDAY not in", values, "beforday");
			return (Criteria) this;
		}

		public Criteria andBefordayBetween(Short value1, Short value2) {
			addCriterion("BEFORDAY between", value1, value2, "beforday");
			return (Criteria) this;
		}

		public Criteria andBefordayNotBetween(Short value1, Short value2) {
			addCriterion("BEFORDAY not between", value1, value2, "beforday");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("NOTE is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("NOTE is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("NOTE =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("NOTE <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("NOTE >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("NOTE >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("NOTE <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("NOTE <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("NOTE like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("NOTE not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("NOTE in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("NOTE not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("NOTE between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("NOTE not between", value1, value2, "note");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SYS_MSG_PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS_MSG_PRODUCER
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 24 14:04:15 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}