package com.chd.hrp.hr.entity.msg;

import java.math.BigDecimal;
import java.util.Date;


public class SysMsgProducer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.ID
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.GROUP_ID
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.HOS_ID
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private Integer hosId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.COPY_CODE
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private String copyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.NAME
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private String producer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.CRON
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private String cron;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.REUSER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private String reuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.REROLE
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private String rerole;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.CREATOR
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private BigDecimal creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.CREATIME
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private Date creatime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.BEFORDAY
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private Short beforday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.STATUS
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS_MSG_PRODUCER.NOTE
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.ID
	 * @return  the value of SYS_MSG_PRODUCER.ID
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.ID
	 * @param id  the value for SYS_MSG_PRODUCER.ID
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.GROUP_ID
	 * @return  the value of SYS_MSG_PRODUCER.GROUP_ID
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.GROUP_ID
	 * @param groupId  the value for SYS_MSG_PRODUCER.GROUP_ID
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.HOS_ID
	 * @return  the value of SYS_MSG_PRODUCER.HOS_ID
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public Integer getHosId() {
		return hosId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.HOS_ID
	 * @param hosId  the value for SYS_MSG_PRODUCER.HOS_ID
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setHosId(Integer hosId) {
		this.hosId = hosId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.COPY_CODE
	 * @return  the value of SYS_MSG_PRODUCER.COPY_CODE
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public String getCopyCode() {
		return copyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.COPY_CODE
	 * @param copyCode  the value for SYS_MSG_PRODUCER.COPY_CODE
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setCopyCode(String copyCode) {
		this.copyCode = copyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.NAME
	 * @return  the value of SYS_MSG_PRODUCER.NAME
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.NAME
	 * @param name  the value for SYS_MSG_PRODUCER.NAME
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.PRODUCER
	 * @return  the value of SYS_MSG_PRODUCER.PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public String getProducer() {
		return producer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.PRODUCER
	 * @param producer  the value for SYS_MSG_PRODUCER.PRODUCER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setProducer(String producer) {
		this.producer = producer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.CRON
	 * @return  the value of SYS_MSG_PRODUCER.CRON
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public String getCron() {
		return cron;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.CRON
	 * @param cron  the value for SYS_MSG_PRODUCER.CRON
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setCron(String cron) {
		this.cron = cron;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.REUSER
	 * @return  the value of SYS_MSG_PRODUCER.REUSER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public String getReuser() {
		return reuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.REUSER
	 * @param reuser  the value for SYS_MSG_PRODUCER.REUSER
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setReuser(String reuser) {
		this.reuser = reuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.REROLE
	 * @return  the value of SYS_MSG_PRODUCER.REROLE
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public String getRerole() {
		return rerole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.REROLE
	 * @param rerole  the value for SYS_MSG_PRODUCER.REROLE
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setRerole(String rerole) {
		this.rerole = rerole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.CREATOR
	 * @return  the value of SYS_MSG_PRODUCER.CREATOR
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public BigDecimal getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.CREATOR
	 * @param creator  the value for SYS_MSG_PRODUCER.CREATOR
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setCreator(BigDecimal creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.CREATIME
	 * @return  the value of SYS_MSG_PRODUCER.CREATIME
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public Date getCreatime() {
		return creatime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.CREATIME
	 * @param creatime  the value for SYS_MSG_PRODUCER.CREATIME
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setCreatime(Date creatime) {
		this.creatime = creatime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.BEFORDAY
	 * @return  the value of SYS_MSG_PRODUCER.BEFORDAY
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public Short getBeforday() {
		return beforday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.BEFORDAY
	 * @param beforday  the value for SYS_MSG_PRODUCER.BEFORDAY
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setBeforday(Short beforday) {
		this.beforday = beforday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.STATUS
	 * @return  the value of SYS_MSG_PRODUCER.STATUS
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.STATUS
	 * @param status  the value for SYS_MSG_PRODUCER.STATUS
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS_MSG_PRODUCER.NOTE
	 * @return  the value of SYS_MSG_PRODUCER.NOTE
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS_MSG_PRODUCER.NOTE
	 * @param note  the value for SYS_MSG_PRODUCER.NOTE
	 * @mbggenerated  Wed Dec 26 17:42:30 CST 2018
	 */
	public void setNote(String note) {
		this.note = note;
	}
}